id: P05A24182
initial_creation_type: input
source_metadata:
  title: 'Asaṅga/Maitreya: Ratnagotravibhāga'
  language: bo
  volumes:
    3da2622863b24d20a8586e3b1a819e72:
      title: CIII_XIV. General Characteristics Of The Buddha’s Properties
      base_file: CIII_XIV. General Characteristics Of The Buddha’s Properties.txt
      work_id: WD424A7ED
    2e7c661efb0544be9b607a23bdae377c:
      title: CIII_XV. 64 Properties of the Buddha
      base_file: CIII_XV. 64 Properties of the Buddha.txt
      work_id: WEC56DE1C
    553a2f4f18b845509aec999381ca00bf:
      title: CII_XII. General Characteristics of the Reality Free from Pollutions
      base_file: CII_XII. General Characteristics of the Reality Free from Pollutions.txt
      work_id: W8286C7A8
    f5402f6a3a5b4e3c8603aa583609d1a2:
      title: CII_XIII. 8 Points on the Undefiled Reality
      base_file: CII_XIII. 8 Points on the Undefiled Reality.txt
      work_id: W9C0C81C6
    23ab80e96a4349e0beef7f29450e06b7:
      title: CIV_XVI. General Characteristics of the Acts of the Buddha
      base_file: CIV_XVI. General Characteristics of the Acts of the Buddha.txt
      work_id: WF7CFC049
    e85d498cf9cc4977bc75d6726c863f02:
      title: CIV_XVII. 9 Illustrations of the Buddha’s Acts
      base_file: CIV_XVII. 9 Illustrations of the Buddha’s Acts.txt
      work_id: WA84B8717
    aaf3c65afcbf4e818a31956281c67297:
      title: CI_I. Introduction
      base_file: CI_I. Introduction.txt
      work_id: WA7129B9A
    5a2e01ecebb0434588dd59bf0af6cd33:
      title: CI_II. The Jewel of the Buddha
      base_file: CI_II. The Jewel of the Buddha.txt
      work_id: W965D9311
    4e9b7d7c817545ad8f15a7c038760d83:
      title: CI_III. The Jewel of the Doctrine
      base_file: CI_III. The Jewel of the Doctrine.txt
      work_id: WDC7CA4BF
    6e43ac0b3bca4064b0e5c5ff05decfdc:
      title: CI_IV. The Jewel of the Community
      base_file: CI_IV. The Jewel of the Community.txt
      work_id: WB2A2DB5B
    fcef6fd92d83473aa364ba7eddbc049e:
      title: CI_IX. The 9 Illustrations on the Germ Covered with Defilements
      base_file: CI_IX. The 9 Illustrations on the Germ Covered with Defilements.txt
      work_id: W309C2D9D
    354f48c2c578432d964a0c49d335df4a:
      title: CI_V. The Three Jewels as Refuges
      base_file: CI_V. The Three Jewels as Refuges.txt
      work_id: WE4498B40
    e00804ebbf9441a1959b6410d045dfa2:
      title: CI_VI. The Germ Of Three Jewels In Four Aspects
      base_file: CI_VI. The Germ Of Three Jewels In Four Aspects.txt
      work_id: W5DADD207
    634bc8b2b4e74507b2573dfde5bc503e:
      title: 'CI_VII. The Sermon: All Living Beings are possessed of The Matrix of
        the Tathāgata'
      base_file: 'CI_VII. The Sermon: All Living Beings are possessed of The Matrix
        of the Tathāgata.txt'
      work_id: WB5B57574
    25f518e808e94b3fb691b4fd039a321d:
      title: CI_VIII. Analysis of the Germ from 10 Points of View
      base_file: CI_VIII. Analysis of the Germ from 10 Points of View.txt
      work_id: W3076965C
    828853295d1b4eea91a448ef6c370cb6:
      title: CI_X. The Essential Characteristics of the Matrix of the Tathāgata
      base_file: CI_X. The Essential Characteristics of the Matrix of the Tathāgata.txt
      work_id: W11096F70
    f49cae9e03ec4ebaad50bb7f24a0d726:
      title: CI_XI. The Purpose of Instruction
      base_file: CI_XI. The Purpose of Instruction.txt
      work_id: WE6BA21AA
    c8832c7ad5b84b1aa339063393154db1:
      title: CV_XVIII. The Merits of Having Faith in the Doctrine of the Essence of
        Buddhahood
      base_file: CV_XVIII. The Merits of Having Faith in the Doctrine of the Essence
        of Buddhahood.txt
      work_id: W00887B80
    af0a4bf0bd9e4805a31205c7041234f9:
      title: Colophon
      base_file: Colophon.txt
      work_id: WCB12B9EB
    b53bd380b8814efb8081732d1d089d2f:
      title: Preface
      base_file: Preface.txt
      work_id: WF249A966
    60869ead409f4d6f989651b472aa865c:
      title: Title
      base_file: Title.txt
      work_id: WAF9DD948
  chapter_to_tile:
    CI: 'Chapter I: The Matrix of the Tathāgata'
    CII: 'Chapter II: The Matrix of the Tathāgata'
    CIII: 'Chapter III: The Properties of the Buddha'
    CIV: 'Chapter IV: The Acts of The Buddha'
    CV: 'Chapter V: The Merits of Faith'
created_at: '2022-03-01T23:02:26.071665'
last_modified_at: '2022-03-01T23:02:26.071673'
